### ISSUE TITLE
Add UI with buttons / editor to add LICENSE and README

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Hub#15]
![image](https://user-images.githubusercontent.com/1951843/116899449-8cae9e00-ac05-11eb-9e9c-7f654cfd4bc6.png)

- [ ] Add ability to add a new README or LICENSE directly from the web UI
- [x] Add ability to edit an existing README or LICENSE from the web UI

**Comment by pierotofy** [comment]
Similar to GitHub editor: https://github.com/DroneDB/Hub/edit/master/README.md

**Comment by pierotofy** [comment]
This one still needs to be implemented @HeDo88TH ? There are no buttons to add LICENSE/README.

**Comment by HeDo88TH** [comment]
Yes, now we have buttons to EDIT not to ADD. I'll take care of it as soon as possible 👍
