### ISSUE TITLE
Improve breadcrumbs

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Hub#36]
The breadcrumbs indicator in the Files tab could be improved to allow navigation back to parents.

E.g. similar to Windows Explorer:

![image](https://user-images.githubusercontent.com/1951843/131165001-24bac46d-5dc9-4a3a-a52c-cac97b5ff1d5.png)

**Comment by HeDo88TH** [comment]
Yes, I received a feedback regarding this. We should make the path support copy/paste to prevent deep drill downs to get to the desired folder.

**Comment by HeDo88TH** [comment]
Closed by https://github.com/DroneDB/CommonUI/pull/12
