### ISSUE TITLE
Contextual tabs

### ISSUE THREAD

**Issue by HeDo88TH** [DroneDB/Hub#40]
Tabs should follow the selection: It's useless to show the 3D tab when no LAZ file is selected. Accordingly, It's useless to show the map tab when no georefereced data is present in the current selection.

**Comment by pierotofy** [comment]
This will be a non-issue for georeferenced LAZ once we add support for EPTTiler into Registry.

Will still be an improvement for non-georeferenced LAZ.

**Comment by pierotofy** [comment]
No longer applicable due to recent redesign.
