### ISSUE TITLE
Show all properties when right-clicking Properties

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Hub#45]
Currently only file type, size are shown.

**Comment by HeDo88TH** [comment]
Closed in https://github.com/DroneDB/CommonUI/pull/10

**Comment by HeDo88TH** [comment]
I tried different approaches but this was the one I chose. We can make a comma separated list but some properties can contain spaces and other stuff. We can use quotes to separate them better but it becomes messy. I'm open to a better approach 👍

**Comment by pierotofy** [comment]
It's a list, so <ul><li></li></ul> for each element?

**Comment by HeDo88TH** [comment]
> It's a list, so `<ul><li>1</li><li>2</li>...</ul>` for each element?

Yes, but it would occupy much space.  My way is more compact.
